# Generated by Django 3.0.3 on 2021-05-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210505_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=32000, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=32000, max_digits=14),
            preserve_default=False,
        ),
    ]
